name: fluttersaurus
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.0.1
  google_fonts: ^2.1.0
  thesaurus_repository:
    path: packages/thesaurus_repository
  shimmer: ^2.0.0
  equatable: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/icons/